torchrun --standalone --nnodes 1 --nproc-per-node 4 ../vla-scripts/finetune_bitnet.py \
  --vla_path /path/to/BitVLA-pretrain-200k \
  --data_root_dir /path/to/modified_libero_rlds/ \
  --dataset_name libero_goal_no_noops \
  --run_root_dir /path/to/save/your/ckpt \
  --use_l1_regression True \
  --warmup_steps 375 \
  --use_lora False \
  --num_images_in_input 2 \
  --use_proprio True \
  --batch_size 2 \
  --grad_accumulation_steps 8 \
  --learning_rate 2e-4 \
  --max_steps 10001 \
  --save_freq 10000 \
  --save_latest_checkpoint_only False \
  --image_aug True \
  --run_id_note your_id
